Areas/Country/Models/LOC_CountryModel.cs
using System.ComponentModel.DataAnnotations;

namespace AdminPanel_UI.Areas.Country.Models
{
    public class LOC_CountryModel
    {
        public int? CountryID { get; set; }
        [Required]
        public string CountryName { get; set; }
        [Required]
        public string CountryCode { get; set; }

        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
    }

    public class LOC_CountryDropDown
    {
        public int? CountryID { get; set; }
        [Required]
        public string CountryName { get; set; }
        public string CountryCode { get; set; }

    }
}

Areas/States/Models/LOC_StateModel.cs
using System.ComponentModel.DataAnnotations;

namespace AdminPanel_UI.Areas.States.Models
{
    public class LOC_StateModel
    {
        public int StateID { get; set; }    
        public string StateName { get; set; } = string.Empty;
        public string StateCode { get; set; }
        public string CountryName { get; set; }
        [Required]
        public string CountryCode { get; set; }

        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace AdminPanel_UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Areas/City/Controllers/LOC_CityController.cs
using AdminPanel_UI.DAL.LOC_CityDAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace AdminPanel_UI.Areas.City.Controllers
{
    [Area("City")]
    [Route("City/[controller]/[action]")]
    public class LOC_CityController : Controller
    {
        LOC_CityDAL dalLOC_CityDAL = new LOC_CityDAL();

        #region LOC_CityList Controller
        public IActionResult LOC_CityList()
        {
            DataTable dt= dalLOC_CityDAL.dbo_PR_LOC_City_SelectAll();
            return View(dt);
        }
        #endregion

        public IActionResult Add()
        {
            return View("AddEditCity");
        }
        public IActionResult AddEditCity()
        {
            return View();
        }
    }
}

Areas/Country/Controllers/LOC_CountryController.cs
using AdminPanel_UI.Areas.Country.Models;
using AdminPanel_UI.DAL.LOC_CountryDAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace AdminPanel_UI.Areas.Country.Controllers
{
    [Area("Country")]
    [Route("Country/[controller]/[action]")]
    public class LOC_CountryController : Controller
    {
        LOC_CountryModel modelLOC_Country =new LOC_CountryModel();
        LOC_CountryDAL dalLOC_CountryDAL = new LOC_CountryDAL();

        #region LOC_CountryList Controller
        public IActionResult LOC_CountryList()
        {
            DataTable dt = dalLOC_CountryDAL.dbo_PR_LOC_Country_SelectAll();
            return View(dt);
        }
        #endregion

        #region Add NAvigator For Render PAge
        public IActionResult Add(int ?CountryID)
        {   


            LOC_CountryModel model=dalLOC_CountryDAL.PR_LOC_Country_SelectByPK(CountryID);
            if (model != null)
            {
                return View("AddEditCountry", model);
            }
            else
            {
                return View("AddEditCountry");
            }
        }
        #endregion

        #region Add /Edit Page Controller
        public IActionResult AddEditCountry(LOC_CountryModel modelLOC_CountryModel)
        {
            if (dalLOC_CountryDAL.SaveCountry(modelLOC_CountryModel))
            {
                if (modelLOC_CountryModel.CountryID == null)
                {
                    TempData["CountryInsertMsg"] = "Record Inserted Successfully";
                    return RedirectToAction("LOC_CountryList");
                }
                else
                    return RedirectToAction("LOC_CountryList");
            }
            return View("AddEditCountry");
        }
        #endregion

        #region Delete 
        public IActionResult Delete(int ?CountryID)
        {
            dalLOC_CountryDAL.PR_LOC_Country_Delete(CountryID);
            return RedirectToAction("LOC_CountryList");
        }
        #endregion
    }
}
    

Areas/States/Controllers/LOC_StateController.cs
using AdminPanel_UI.DAL.LOC_StateDAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace AdminPanel_UI.Areas.States.Controllers
{
    [Area("States")]
    [Route("States/[controller]/[action]")]
    public class LOC_StateController : Controller
    {
        LOC_StateDAL dalLOC_StateDAL = new LOC_StateDAL();

        #region LOC_StateList
        public IActionResult LOC_StateList()
        {
            DataTable dt = dalLOC_StateDAL.dbo_PR_LOC_State_SelectAll();
            return View(dt);
        }
        #endregion
        public IActionResult Add()
        {
            return View("AddEditState");
        }
        public IActionResult AddEditState()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using AdminPanel_UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdminPanel_UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Areas/City/Views/LOC_City/AddEditCity.cshtml
@{
    ViewData["Title"] = "Add/Edit State";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="fw-bold" ">Add / Edit City</h4>
<hr>
<form>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">City Name </label>
        <div class="col-sm-8">
            <input type="text" class="form-control" placeholder=" City Name" />
@*<span asp-validation-for="CountryName" class="text-danger"></span>*@
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">City Code </label>
        <div class="col-sm-8">
            <input type="text" class="form-control" placeholder=" City Code" />
@*<span asp-validation-for="CountryCode" class="text-danger"></span>*@
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Select State</label>
        <div class="dropdown col-sm-8">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown button
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Select Country</label>
        <div class="dropdown col-sm-8">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown button
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/City/Views/LOC_City/LOC_CityList.cshtml
@using System.Data;
@model DataTable
<br />
<form class="row row-cols-lg-auto g-3 align-items-center">
    <h1 class="text-center">City List</h1>
    <hr />
    <div class="text-center">
        <input type="submit" class="btn btn-primary m-4 " value="ADD City" asp-action="Add" asp-controller="LOC_City" asp-area="City">
    </div>
</form>
<br/>
<table class="table">
    <thead>
        <tr>
            @*<th scope="col">CityID</th>
            <th scope="col">StateID</th>*@
            <th scope="col">CityName </th>
            <th scope="col">CityCode </th>
            <th scope="col">CountryName</th>
            <th scope="col">StateName</th>
            <th scope="col">StateCode </th>
            <th scope="col">Created </th>
            <th scope="col">Modified </th>
            <th scope="col">Actions </th>
        </tr>
    </thead>
    <tbody>
        @foreach (DataRow dr in Model.Rows)
        {
            <tr>
                @*<td>@dr["CityID"]</td>
                <td>@dr["StateID"]</td>*@
                <td>@dr["CityName"]</td>
                <td>@dr["CityCode"]</td>
                <td>@dr["CountryName"]</td>
                <td>@dr["StateName"]</td>
                <td>@dr["StateCode"]</td>
                <td>@Convert.ToDateTime(dr["Created"]).ToString("MM/dd/yyyy H:mm")</td>
                <td>@Convert.ToDateTime(dr["Modified"]).ToString("MM/dd/yyyy H:mm")</td>
                <td>
                    <form >
                        @*<input type="hidden" name="CountryID" value="@Convert.ToInt32(dr["CountryID"])">*@
                        <button type="submit" class="btn btn-danger btn-xs">delete</button>
                        <a class="btn btn-info btn-xs" >edit</a>
                    </form>
                </td>

            </tr>
        }
    </tbody>
</table>

Areas/Country/Views/LOC_Country/AddEditCountry.cshtml
@using AdminPanel_UI.Areas.Country.Models;
@{
    ViewData["Title"] = "Add/Edit Country";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="fw-bold" ">Add / Edit Country</h4>
<hr />
@model LOC_CountryModel
@*<h4>@TempData["CountryInsertMsg"]</h4>*@
<form method="post" asp-controller="LOC_Country" asp-action="AddEditCountry">
    @Html.HiddenFor(x=>x.CountryID)
    <div class="form-group row">
        <label  class="col-sm-2 col-form-label">Country Name </label>
        <div class="col-sm-8">
            <input type="text" class="form-control"  placeholder=" Country Name" asp-for="CountryName">
            <span asp-validation-for="CountryName" class="text-danger"></span>
        </div>
    </div>
    
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Country Code </label>
        <div class="col-sm-8">
            <input type="text" class="form-control" placeholder=" Country Code" asp-for="CountryCode">
            <span asp-validation-for="CountryCode" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary" >Submit</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Country/Views/LOC_Country/LOC_CountryList.cshtml
@using System.Data
@model DataTable
@{
    ViewData["Title"] = " Country List ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<form class="row row-cols-lg-auto g-3 align-items-center">
    <h1 class="text-center">Country List</h1>
    <hr />
    <div class="text-center">
        <input type="submit" class="btn btn-primary m-4 " value="ADD Country" asp-action="Add" asp-controller="LOC_Country" asp-area="Country">
    </div>
</form>

<br>

<table class="table">
    <thead>
        <tr>
            @*<th scope="col">CountryID</th>*@
            <th scope="col">CountryName</th>
            <th scope="col">CountryCode</th>
            <th scope="col">Created</th>
            <th scope="col">Modified At </th>
            <th scope="col">Actions </th>


        </tr>
    </thead>
    <tbody>
        @foreach (DataRow dr in Model.Rows)
        {
            <tr>
                @*<td>@dr["CountryID"]</td>*@
                <td>@dr["CountryName"]</td>
                <td>@dr["CountryCode"]</td>
                <td>@Convert.ToDateTime(dr["Created"]).ToString("MM/dd/yyyy H:mm")</td>
                <td>@Convert.ToDateTime(dr["Modified"]).ToString("MM/dd/yyyy H:mm   ")</td>
                <td>
                    <form method="post" asp-controller="LOC_Country" asp-action="Delete">
                        <input type="hidden" name="CountryID" value="@Convert.ToInt32(dr["CountryID"])">
                        <button type="submit" class="btn btn-danger btn-xs">delete</button>
                        <a class="btn btn-info btn-xs" asp-controller="LOC_Country" asp-action="Add" asp-route-countryid="@Convert.ToInt32(dr["CountryID"])">edit</a>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>


@*@section Scripts{
<script>
    function displayPopUp(){
            Swal.fire({
                title: 'Do you want to save the changes?',
                showDenyButton: true,
                showCancelButton: true,
                confirmButtonText: 'Save',
                denyButtonText: `Don't save`,
            }).then((result) => {
                /* Read more about isConfirmed, isDenied below */
                if (result.isConfirmed) {
                    Swal.fire('Saved!', '', 'success')
                } else if (result.isDenied) {
                    Swal.fire('Changes are not saved', '', 'info')
                }
            })
    }
</script>
}*@

Areas/States/Views/LOC_State/AddEditState.cshtml
@{
    ViewData["Title"] = "Add/Edit State";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="fw-bold" ">Add / Edit State</h4>
<hr>
<form>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">State Name </label>
        <div class="col-sm-8">
            <input type="text" class="form-control" placeholder=" State Name"/>
@*<span asp-validation-for="CountryName" class="text-danger"></span>*@
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">State Code </label>
        <div class="col-sm-8">
            <input type="text" class="form-control" placeholder=" State Code"/>
@*<span asp-validation-for="CountryCode" class="text-danger"></span>*@
        </div>
    </div>      
    <br/>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Select Country</label>
        <div class="dropdown col-sm-8">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown button
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/States/Views/LOC_State/LOC_StateList.cshtml
@using System.Data
@model DataTable
<br />
<form class="row row-cols-lg-auto g-3 align-items-center">
    <h1 class="text-center">State List</h1>
    <hr />
    <div class="text-center">
        <input type="submit" class="btn btn-primary m-4 " value="ADD State" asp-action="Add" asp-controller="LOC_State" asp-area="States">
    </div>
</form>

<br>

<table class="table">
    <thead>
        <tr>
            @*<th scope="col">StateID</th>*@
            <th scope="col">CountryName</th>
            <th scope="col">CountryCode</th>
            <th scope="col">StateName</th>
            <th scope="col">StateCode</th>
            <th scope="col">Created</th>
            <th scope="col">Modified</th>
        </tr>
    </thead>
    <tbody>
        @foreach (DataRow dr in Model.Rows)
        {
            <tr>
                @*<td>@dr["StateID"]</td>*@
                <td>@dr["CountryName"]</td>
                <td>@dr["CountryCode"]</td>
                <td>@dr["StateName"]</td>
                <td>@dr["StateCode"]</td>
                <td>@Convert.ToDateTime(dr["Created"]).ToString("MM/dd/yyyy H:mm")</td>
                <td>@Convert.ToDateTime(dr["Modified"]).ToString("MM/dd/yyyy H:mm")</td>
                <td>
                    <form>
                        @*<input type="hidden" name="CountryID" value="@Convert.ToInt32(dr["CountryID"])">*@
                        <button type="submit" class="btn btn-danger btn-xs">delete</button>
                        <a class="btn btn-info btn-xs">edit</a>
                    </form>
                </td>
            </tr>
        }

    </tbody>
</table>

Views/Home/Index.cshtml
<h1>This Is AddressBook</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminPanel_UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminPanel_UI.styles.css" asp-append-version="true" />
    <meta charset="utf-8" />
    <title>Metronic Admin Theme #1 | Admin Dashboard 3</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="Preview page of Metronic Admin Theme #1 for statistics, charts, recent events and reports" name="description" />
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&amp;subset=all" rel="stylesheet" type="text/css" />
    <link href="~/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="~/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLU

    GINS -->
    <link href="~/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css" rel="stylesheet" type="text/css" />
    <link href="~/global/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
    <link href="~/global/plugins/fullcalendar/fullcalendar.min.css" rel="stylesheet" type="text/css" />
    <link href="~/global/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN THEME GLOBAL STYLES -->
    <link href="~/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
    <link href="~/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
    <!-- END THEME GLOBAL STYLES -->
    <!-- BEGIN THEME LAYOUT STYLES -->
    <link href="~/layouts/layout/css/layout.min.css" rel="stylesheet" type="text/css" />
    <link href="~/layouts/layout/css/themes/darkblue.min.css" rel="stylesheet" type="text/css" id="style_color" />
    <link href="~/layouts/layout/css/custom.min.css" rel="stylesheet" type="text/css" />
    <!-- END THEME LAYOUT STYLES -->
    <link rel="shortcut icon" href="favicon.ico" />
</head>
<!-- END HEAD -->
<body>
    <div class="clearfix"> </div>
    <!-- END HEADER & CONTENT DIVIDER -->
    <!-- BEGIN CONTAINER -->
    <div class="page-container">
        <!-- BEGIN SIDEBAR -->
        <div class="page-sidebar-wrapper">
            <!-- BEGIN SIDEBAR -->
            <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
            <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
            <div class="page-sidebar navbar-collapse collapse">
                <!-- BEGIN SIDEBAR MENU -->
                <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
                <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
                <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
                <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
                <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
                <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                <ul class="page-sidebar-menu  page-header-fixed page-sidebar-menu-hover-submenu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
                    <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
                    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                    <li class="sidebar-toggler-wrapper hide">
                        <div class="sidebar-toggler">
                            <span></span>
                        </div>
                    </li>
                    <!-- END SIDEBAR TOGGLER BUTTON -->
                    <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
                    <li class="nav-item start active open">
                        <a href="javascript:;" class="nav-link nav-toggle">
                            <i class="icon-home"></i>
                            <span class="title">AddressBook</span>
                            <span class="selected"></span>
                            <span class="arrow open"></span>
                        </a>
                        <ul class="sub-menu">
                            <li class="nav-item start ">
                                <a asp-action="LOC_CountryList" asp-controller="LOC_Country" asp-area="Country" class="nav-link ">
                                    <i class="icon-bar-chart"></i>
                                    <span class="title">Country</span>
                                </a>
                            </li>
                            <li class="nav-item start ">
                                <a asp-action="LOC_StateList" asp-area="States" asp-controller="LOC_State" class="nav-link ">
                                    <i class="icon-bulb"></i>
                                    <span class="title">State</span>
                                </a>
                            </li>
                            <li class="nav-item start active open">
                                <a asp-action="LOC_CityList" asp-area="City" asp-controller="LOC_City" class="nav-link ">
                                    <i class="icon-graph"></i>
                                    <span class="title">City</span>
                                    <span class="selected"></span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <!-- END SIDEBAR MENU -->
                <!-- END SIDEBAR MENU -->
            </div>
            <!-- END SIDEBAR -->
        </div>
        <div class="page-content-wrapper">
            <!-- BEGIN CONTENT BODY -->
            <div class="page-content">
                @RenderBody()
            </div>
        </div>
        </div>
        <!-- END SIDEBAR -->
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
</body>
</html>


@*<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminPanel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminPanel.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#"> &nbsp; Location</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-action="LOC_CountryList" asp-area="Country" asp-controller="LOC_Country">Country </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-action="LOC_StateList" asp-area="States" asp-controller="LOC_State">State </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-action="LOC_CityList" asp-area="City" asp-controller="LOC_City">City </a>
                    </li>
                </ul>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
*@